# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0002_auto_20170320_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_text',
            new_name='tag_name',
        ),
    ]
