# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0003_auto_20170320_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docsearch.Country'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docsearch.Country'),
        ),
    ]
