# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0004_auto_20170320_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
    ]
