# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0005_auto_20170320_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
