# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0007_auto_20170321_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='citation_index',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
